language: julia
julia:
  - nightly
  - 1.1

coveralls: true

os:
  - linux
  - osx

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia docs/make.jl
      after_success: skip

